---
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'config/**/*'
    - 'public/**/*'
    - 'build/**/*'

Metrics/CyclomaticComplexity:
  Severity: refactor
  Max: 8

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Severity: convention
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150
  Severity: refactor

Metrics/MethodLength:
  Max: 15
  Severity: refactor

Metrics/ParameterLists:
  Max: 5
  Severity: refactor

Metrics/PerceivedComplexity:
  Max: 10
  Severity: refactor

Lint/Void:
  Exclude: ['**/*_spec.rb']

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/UselessAssignment:
  Severity: error

Lint/ShadowingOuterLocalVariable:
  Severity: convention

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false
  Severity: refactor

Style/GuardClause:
  MinBodyLength: 3

Style/Lambda:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

# This one is usefull for class attr_*
Style/TrivialAccessors:
  AllowDSLWriters: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedLastArgumentHashStyle: always_ignore

Style/ModuleFunction:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Naming/PredicateName:
  Severity: refactor

layout/IndentHash:
  EnforcedStyle: consistent

Style/MultilineBlockChain:
  Severity: refactor

Lint/AssignmentInCondition:
  Enabled: false

Style/Alias:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
    '%': '{}'

Style/CollectionMethods:
  PreferredMethods:
    reduce: inject
    collect: map
    collect!: 'map!'
    detect: find
    detect!: 'find!'
    find_all: select
    find_all!: 'select!'

Style/DoubleNegation:
  Severity: refactor

Style/SignalException:
  EnforcedStyle: only_raise

Layout/DotPosition:
  EnforcedStyle: trailing

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: true

# It doesnt handle cases when we want to align multiple methods call into a table like
Layout/SpaceBeforeFirstArg:
  Enabled: false

# replaces $1 x Regexp.last_match[1]
Style/PerlBackrefs:
  Enabled: false

# There are valid cases (eg. Date.parse(date) rescue nil)
Style/RescueModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
